### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by a-kong** [annabelle-ep/dsci-310-group-04#17]
### Analysis: Methods & Results
- [x] visualizations are difficult to read

### GitHub Project board
- [x] missing Project board

### Analysis can be run reproducibly using documentation provided in the README
- [x] difficult to follow steps to reproduce environment
	- you can cut down on your getting 'Getting Started' section by jumping straight to step 4. 
	- make it easier by explicitly stating the command to clone your repo.
