### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by a-kong** [annabelle-ep/dsci-310-group-04#38]
### Functions are well documented
- [x] missing function summary for `classy_read.R`
- [x] missing examples for `classy_read.R` and `create_faceted_hist_plot.R`
- [x] reword the title for `create_faceted_hist_plot.R` and add a description

### Code is called in the analysis
- [x] only 2/3 functions are called
- [x] for readability, put all `source` lines at the beginning 

### Helper data for tests is tractable and reproducible
- [x] helper data is not tractable and not reproducible

### Tests are written for each function, and work expected
- [x] missing test file for 1 function
- [x] some tests fail
- [x] helper data should not be in the test file

### Tests suite is of high quality
- [x] functions require more thorough testing

### Project file and directory structure organization
- [x] `tests/testthat` folders should not be in `R` folder

### GitHub Issue Milestones
- [x] missing use of milestones

### GitHub Release
- [x] suggestion: pick a naming style that enumerates each milestone to make it more clear (ex: milestone 1: 0.1.0, milestone 2: 0.2.0, etc,...)

### Analysis can be run reproducibly using documentation provided in the README
- [x] pin version number for packages

**Comment by oliviacyp** [comment]
Ask for clarification on helper data reproducibility
