### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by a-kong** [annabelle-ep/dsci-310-group-04#53]
### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.
- [x] don't need to state the references in the References section, since it'll automatically generate for you

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis.
- [x] missing documentation in `Makefile`

### GitHub Issue Milestones
- [x] barely used

### Follows GitHub flow version control workflow.
- [x] make sure that you don't merge your own pull requests

### Dependencies have been updated (so it include the test libraries)
- [x] R Markdown requires updated version

### Project file and directory structure organization.
- [x] put notebooks in a `notebooks` or `doc` directory

### Analysis can be run reproducibly using documentation provided in the README
- [x] missing `Makefile` instructions

### Address Feedback from Milestone 1 and 2
- marks have been updated on Canvas
- if you have any questions, please let me know!
